### PR TITLE
Use new Symmetric Hessian

### PR DESCRIPTION
**Pull request by abelsiqueira**
Implementing https://github.com/JuliaSmoothOptimizers/NLPModels.jl/pull/354

### CODE REVIEW

**Comment by tmigot** [comment]
Very cool PR, thanks! I believe the error in the consistency tests is that the `(hess_structure, hess_coord)` triplet no longer corresponds to the result of `hess`.

Then, this is also breaking [ADNLPModels.jl PR #18](https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/pull/18).

**Comment by geoffroyleconte** [comment]
Hi, thanks for this PR! Could we upgrade directly to NLPModels 0.17 and NLPModelsModifiers 0.4, so that it is possible to make the changes relative to LinearOperators 2 and the parametric NLPModelsMeta to all the packages? I think we would only have to change the Project.toml file to pass these tests.

**Comment by abelsiqueira** [comment]
> Hi, thanks for this PR! Could we upgrade directly to NLPModels 0.17 and NLPModelsModifiers 0.4, so that it is possible to make the changes relative to LinearOperators 2 and the parametric NLPModelsMeta to all the packages? I think we would only have to change the Project.toml file to pass these tests.

Just did it! I was waiting for NLPModelsModifiers 0.4.0 :)

**Comment by geoffroyleconte** [comment]
> 
> 
> > Hi, thanks for this PR! Could we upgrade directly to NLPModels 0.17 and NLPModelsModifiers 0.4, so that it is possible to make the changes relative to LinearOperators 2 and the parametric NLPModelsMeta to all the packages? I think we would only have to change the Project.toml file to pass these tests.
> 
> Just did it! I was waiting for NLPModelsModifiers 0.4.0 :)

Nice thank you!

**Pull request merged**
