### PR TITLE
 Parametric NLPModelMeta

### PR DESCRIPTION
**Pull request by tmigot**
Follows [NLPModels.jl PR #353](https://github.com/JuliaSmoothOptimizers/NLPModels.jl/pull/353) with parametric meta.

Should be merged after [NLPModelsModifiers.jl PR #12](https://github.com/JuliaSmoothOptimizers/NLPModelsModifiers.jl/pull/12).

### CODE REVIEW

**Review by abelsiqueira — COMMENTED** [review]
Thanks again.
I think that we'll need specialized constructors as well. Not sure, because it depends on how and what we test with other packages. In particular, multi-precision tests. Otherwise, we can simply say
```
mutable struct SomeProblem <: AbstractNLPModel{Float64, Vector{Float64}}
```

**Comment by amontoison** [comment]
Thanks Tangi ! I will update `NLPModelsJuMP` after this PR.

**Comment by tmigot** [comment]
> Thanks again.
> I think that we'll need specialized constructors as well. Not sure, because it depends on how and what we test with other packages. In particular, multi-precision tests. Otherwise, we can simply say
> 
> ```
> mutable struct SomeProblem <: AbstractNLPModel{Float64, Vector{Float64}}
> ```

I added specialized constructors, just because it is more general this way. In case, we add further mutli-precision tests as you mentioned.

**Review by abelsiqueira — APPROVED** [review]
Thanks

**Pull request merged**
